import type { Place } from '@/types/place'
import { BAHIR_DAR_CENTER } from '@/constants'
import { HOTEL_NIGHT_ETB, FOOD_PERSON_DAY_ETB, ATTRACTION_ETB } from '@/data/bahirDarPrices'

/** Client-side DEMO places with research-based price hints (ETB). Not live bookings. */
export const DEMO_PLACES: Place[] = [
  {
    id: 'demo-lake-tana',
    name: 'Lake Tana (DEMO)',
    slug: 'lake-tana-demo',
    category_id: 'demo-attraction',
    description:
      'DEMO — Ethiopia\'s largest lake. Boat to monasteries: shared half-day often ' +
      `${ATTRACTION_ETB.lakeTanaBoatSharedHalfDay.min}–${ATTRACTION_ETB.lakeTanaBoatSharedHalfDay.max} ETB; private higher. Verify operators locally.`,
    short_description: 'Largest lake in Ethiopia',
    address: 'Bahir Dar, Amhara',
    latitude: 11.6167,
    longitude: 37.4,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: ATTRACTION_ETB.monasteryEntry.typical,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
    attraction: {
      id: 'demo-att-1',
      place_id: 'demo-lake-tana',
      attraction_type: 'nature',
      entrance_fee: ATTRACTION_ETB.monasteryEntry.typical,
      recommended_duration: 'Half day – full day',
      best_time_to_visit: 'Morning',
      historical_information: null,
      safety_information: 'Use verified boat operators; agree price before boarding',
      accessibility: null,
    },
  },
  {
    id: 'demo-blue-nile',
    name: 'Blue Nile Falls Viewpoint (DEMO)',
    slug: 'blue-nile-falls-demo',
    category_id: 'demo-attraction',
    description:
      `DEMO — Tis Issat. Entry often ${ATTRACTION_ETB.blueNileFallsEntry.min}–${ATTRACTION_ETB.blueNileFallsEntry.max} ETB/adult; guide ~${ATTRACTION_ETB.blueNileFallsGuide.typical} ETB/group; private car round trip ~${ATTRACTION_ETB.privateCarFallsRoundTrip.min}–${ATTRACTION_ETB.privateCarFallsRoundTrip.max} ETB. Confirm all fees on site.`,
    short_description: 'Tissisat — the smoking water',
    address: 'Near Bahir Dar (Tis Abay)',
    latitude: 11.489,
    longitude: 37.587,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: ATTRACTION_ETB.blueNileFallsEntry.typical,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
    attraction: {
      id: 'demo-att-2',
      place_id: 'demo-blue-nile',
      attraction_type: 'nature',
      entrance_fee: ATTRACTION_ETB.blueNileFallsEntry.typical,
      recommended_duration: '2–4 hours',
      best_time_to_visit: 'After rainy season for stronger flow',
      historical_information: null,
      safety_information: 'Steep paths; spray in wet season',
      accessibility: 'Limited',
    },
  },
  {
    id: 'demo-hotel-1',
    name: 'Lakeside Hotel Example (DEMO)',
    slug: 'lakeside-hotel-demo',
    category_id: 'demo-hotel',
    description: `DEMO mid-range lakeside-style stay. Typical band ${HOTEL_NIGHT_ETB.mid.min}–${HOTEL_NIGHT_ETB.mid.max} ETB/night (research snapshot). Not a real booking.`,
    short_description: 'Example lakeside stay',
    address: 'Bahir Dar lakeside (approximate)',
    latitude: 11.598,
    longitude: 37.385,
    phone: null,
    email: null,
    website: null,
    price_level: 3,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-hotel',
      name: 'Hotels',
      slug: 'hotel',
      icon: 'Hotel',
      description: null,
      sort_order: 1,
    },
    hotel: {
      id: 'demo-h-1',
      place_id: 'demo-hotel-1',
      star_rating: 3,
      minimum_price: HOTEL_NIGHT_ETB.mid.min,
      maximum_price: HOTEL_NIGHT_ETB.mid.max,
      amenities: ['WiFi', 'Restaurant', 'Lake view'],
      check_in: '14:00',
      check_out: '11:00',
    },
  },
  {
    id: 'demo-hotel-2',
    name: 'City Center Guesthouse (DEMO)',
    slug: 'city-guesthouse-demo',
    category_id: 'demo-hotel',
    description: `DEMO budget guesthouse. Typical ${HOTEL_NIGHT_ETB.budget.min}–${HOTEL_NIGHT_ETB.budget.max} ETB/night.`,
    short_description: 'Example budget stay',
    address: 'Central Bahir Dar (approximate)',
    latitude: 11.591,
    longitude: 37.392,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-hotel',
      name: 'Hotels',
      slug: 'hotel',
      icon: 'Hotel',
      description: null,
      sort_order: 1,
    },
    hotel: {
      id: 'demo-h-2',
      place_id: 'demo-hotel-2',
      star_rating: 2,
      minimum_price: HOTEL_NIGHT_ETB.budget.min,
      maximum_price: HOTEL_NIGHT_ETB.budget.max,
      amenities: ['WiFi'],
      check_in: '13:00',
      check_out: '10:00',
    },
  },
  {
    id: 'demo-rest-1',
    name: 'Traditional Ethiopian Kitchen (DEMO)',
    slug: 'traditional-kitchen-demo',
    category_id: 'demo-restaurant',
    description: `DEMO local restaurant. Plates often 50–350 ETB; daily food budget band ~${FOOD_PERSON_DAY_ETB.budget.typical}–${FOOD_PERSON_DAY_ETB.mid.typical} ETB/person.`,
    short_description: 'Injera & traditional dishes (example)',
    address: 'Bahir Dar (approximate)',
    latitude: 11.595,
    longitude: 37.388,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-restaurant',
      name: 'Restaurants',
      slug: 'restaurant',
      icon: 'UtensilsCrossed',
      description: null,
      sort_order: 2,
    },
    restaurant: {
      id: 'demo-r-1',
      place_id: 'demo-rest-1',
      cuisine_type: 'Ethiopian',
      minimum_price: 80,
      maximum_price: 400,
      vegetarian: true,
      traditional_food: true,
      delivery_available: false,
      reservation_available: false,
    },
  },
  {
    id: 'demo-bank-1',
    name: 'Commercial Bank Branch (DEMO)',
    slug: 'cbe-branch-demo',
    category_id: 'demo-bank',
    description: 'DEMO bank branch marker only.',
    short_description: 'Example bank branch',
    address: 'Main street, Bahir Dar (approximate)',
    latitude: 11.593,
    longitude: 37.391,
    phone: null,
    email: null,
    website: null,
    price_level: null,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-bank',
      name: 'Banks',
      slug: 'bank',
      icon: 'Building2',
      description: null,
      sort_order: 5,
    },
    bank: {
      id: 'demo-b-1',
      place_id: 'demo-bank-1',
      bank_name: 'Example Bank',
      has_atm: true,
      has_foreign_exchange: true,
      is_atm_only: false,
    },
  },
  {
    id: 'demo-atm-1',
    name: 'ATM — City Center (DEMO)',
    slug: 'atm-center-demo',
    category_id: 'demo-atm',
    description: 'DEMO ATM marker.',
    short_description: 'Example ATM',
    address: 'Bahir Dar center (approximate)',
    latitude: 11.594,
    longitude: 37.3905,
    phone: null,
    email: null,
    website: null,
    price_level: null,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-atm',
      name: 'ATMs',
      slug: 'atm',
      icon: 'CreditCard',
      description: null,
      sort_order: 6,
    },
    bank: {
      id: 'demo-b-2',
      place_id: 'demo-atm-1',
      bank_name: 'Example ATM',
      has_atm: true,
      has_foreign_exchange: false,
      is_atm_only: true,
    },
  },
  {
    id: 'demo-center',
    name: 'Bahir Dar City Center (DEMO)',
    slug: 'bahir-dar-center-demo',
    category_id: 'demo-attraction',
    description: 'DEMO city center reference point.',
    short_description: 'City center',
    address: 'Bahir Dar',
    latitude: BAHIR_DAR_CENTER.lat,
    longitude: BAHIR_DAR_CENTER.lng,
    phone: null,
    email: null,
    website: null,
    price_level: null,
    entrance_fee: 0,
    currency: 'ETB',
    verified: false,
    featured: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
  },
]

export function demoPlacesByCategory(slug: string): Place[] {
  return DEMO_PLACES.filter((p) => p.category?.slug === slug)
}
