import type { Place } from '@/types/place'
import { BAHIR_DAR_CENTER } from '@/constants'
import { HOTEL_NIGHT_ETB, FOOD_PERSON_DAY_ETB, ATTRACTION_ETB } from '@/data/bahirDarPrices'

/**
 * Built-in Bahir Dar guide places — real landmarks + planning fixtures.
 * Shown instantly (no network). Commercial names with (DEMO) are not live bookings.
 */
export const DEMO_PLACES: Place[] = [
  {
    id: 'demo-lake-tana',
    name: 'Lake Tana',
    slug: 'lake-tana',
    category_id: 'demo-attraction',
    description:
      'Ethiopia’s largest lake. Boat to monasteries: shared half-day often ' +
      `${ATTRACTION_ETB.lakeTanaBoatSharedHalfDay.min}–${ATTRACTION_ETB.lakeTanaBoatSharedHalfDay.max} ETB; private higher. Verify operators locally.`,
    short_description: 'Largest lake in Ethiopia · monasteries',
    address: 'Lake Tana, Bahir Dar',
    latitude: 11.6167,
    longitude: 37.4,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: ATTRACTION_ETB.monasteryEntry.typical,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
    attraction: {
      id: 'demo-att-1',
      place_id: 'demo-lake-tana',
      attraction_type: 'nature',
      entrance_fee: ATTRACTION_ETB.monasteryEntry.typical,
      recommended_duration: 'Half day – full day',
      best_time_to_visit: 'Morning',
      historical_information: 'Source region of the Blue Nile; island monasteries.',
      safety_information: 'Use verified boat operators; agree price before boarding',
      accessibility: 'Boat for islands',
    },
  },
  {
    id: 'demo-blue-nile',
    name: 'Blue Nile Falls (Tis Issat)',
    slug: 'blue-nile-falls-tis-issat',
    category_id: 'demo-attraction',
    description:
      `Tis Issat. Entry often ${ATTRACTION_ETB.blueNileFallsEntry.min}–${ATTRACTION_ETB.blueNileFallsEntry.max} ETB/adult; guide ~${ATTRACTION_ETB.blueNileFallsGuide.typical} ETB/group; private car round trip ~${ATTRACTION_ETB.privateCarFallsRoundTrip.min}–${ATTRACTION_ETB.privateCarFallsRoundTrip.max} ETB. Confirm all fees on site.`,
    short_description: 'Tis Issat · day trip from Bahir Dar',
    address: 'Tis Abay / Tis Issat, near Bahir Dar',
    latitude: 11.489,
    longitude: 37.587,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: ATTRACTION_ETB.blueNileFallsEntry.typical,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
    attraction: {
      id: 'demo-att-2',
      place_id: 'demo-blue-nile',
      attraction_type: 'nature',
      entrance_fee: ATTRACTION_ETB.blueNileFallsEntry.typical,
      recommended_duration: '2–4 hours',
      best_time_to_visit: 'After rainy season for stronger flow',
      historical_information: null,
      safety_information: 'Steep paths; spray in wet season',
      accessibility: 'Limited',
    },
  },
  {
    id: 'demo-bezawit',
    name: 'Bezawit Palace Viewpoint',
    slug: 'bezawit-palace-viewpoint',
    category_id: 'demo-attraction',
    description: `Hilltop view of the Blue Nile outlet and Lake Tana. Often free or small fee (~${ATTRACTION_ETB.bezawitHill.typical} ETB).`,
    short_description: 'City viewpoint · Nile outlet',
    address: 'Bezawit Hill, Bahir Dar',
    latitude: 11.6015,
    longitude: 37.4025,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: ATTRACTION_ETB.bezawitHill.typical,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
    attraction: {
      id: 'demo-att-3',
      place_id: 'demo-bezawit',
      attraction_type: 'viewpoint',
      entrance_fee: ATTRACTION_ETB.bezawitHill.typical,
      recommended_duration: '45–90 minutes',
      best_time_to_visit: 'Sunrise or sunset',
      historical_information: null,
      safety_information: 'Steep sections after rain',
      accessibility: 'Limited',
    },
  },
  {
    id: 'demo-ura',
    name: 'Ura Kidane Mehret Monastery',
    slug: 'ura-kidane-mehret',
    category_id: 'demo-attraction',
    description: `Lake Tana / Zege monastery known for murals. Typical entry ~${ATTRACTION_ETB.monasteryEntry.min}–${ATTRACTION_ETB.monasteryEntry.max} ETB plus boat.`,
    short_description: 'Lake Tana monastery · murals',
    address: 'Zege / Lake Tana islands',
    latitude: 11.695,
    longitude: 37.335,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: ATTRACTION_ETB.monasteryEntry.typical,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
    attraction: {
      id: 'demo-att-4',
      place_id: 'demo-ura',
      attraction_type: 'religious',
      entrance_fee: ATTRACTION_ETB.monasteryEntry.typical,
      recommended_duration: '2–4 hours with boat',
      best_time_to_visit: 'Morning',
      historical_information: 'Celebrated mural art and circular church form.',
      safety_information: 'Modest dress; boat safety',
      accessibility: 'Boat + walking paths',
    },
  },
  {
    id: 'demo-nile-outlet',
    name: 'Blue Nile Bridge / Outlet',
    slug: 'blue-nile-bridge-outlet',
    category_id: 'demo-attraction',
    description: 'Where Lake Tana feeds the Blue Nile. Popular photo stop; combine with Bezawit.',
    short_description: 'Nile outlet · photo stop',
    address: 'Blue Nile outlet, Bahir Dar',
    latitude: 11.605,
    longitude: 37.405,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: 0,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
  },
  {
    id: 'demo-market',
    name: 'Bahir Dar Central Market',
    slug: 'bahir-dar-central-market',
    category_id: 'demo-shopping',
    description: 'Local market for produce, spices, coffee, and household goods. Watch belongings; bargain politely.',
    short_description: 'Local market · produce & crafts',
    address: 'Central Bahir Dar',
    latitude: 11.5925,
    longitude: 37.388,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: 0,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-shopping',
      name: 'Shopping',
      slug: 'shopping',
      icon: 'ShoppingBag',
      description: null,
      sort_order: 10,
    },
  },
  {
    id: 'demo-hotel-1',
    name: 'Lakeside View Hotel (DEMO)',
    slug: 'lakeside-view-hotel-demo',
    category_id: 'demo-hotel',
    description: `Planning example mid-range lakeside stay. Typical band ${HOTEL_NIGHT_ETB.mid.min}–${HOTEL_NIGHT_ETB.mid.max} ETB/night. Not a live booking.`,
    short_description: 'Planning · lakeside stay band',
    address: 'Bahir Dar lakeside',
    latitude: 11.598,
    longitude: 37.385,
    phone: null,
    email: null,
    website: null,
    price_level: 3,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-hotel',
      name: 'Hotels',
      slug: 'hotel',
      icon: 'Hotel',
      description: null,
      sort_order: 1,
    },
    hotel: {
      id: 'demo-h-1',
      place_id: 'demo-hotel-1',
      star_rating: 3,
      minimum_price: HOTEL_NIGHT_ETB.mid.min,
      maximum_price: HOTEL_NIGHT_ETB.mid.max,
      amenities: ['WiFi', 'Restaurant', 'Lake view'],
      check_in: '14:00',
      check_out: '11:00',
    },
  },
  {
    id: 'demo-hotel-2',
    name: 'City Center Guesthouse (DEMO)',
    slug: 'city-center-guesthouse-demo',
    category_id: 'demo-hotel',
    description: `Planning example budget guesthouse. Typical ${HOTEL_NIGHT_ETB.budget.min}–${HOTEL_NIGHT_ETB.budget.max} ETB/night.`,
    short_description: 'Planning · budget stay',
    address: 'Central Bahir Dar',
    latitude: 11.591,
    longitude: 37.392,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-hotel',
      name: 'Hotels',
      slug: 'hotel',
      icon: 'Hotel',
      description: null,
      sort_order: 1,
    },
    hotel: {
      id: 'demo-h-2',
      place_id: 'demo-hotel-2',
      star_rating: 2,
      minimum_price: HOTEL_NIGHT_ETB.budget.min,
      maximum_price: HOTEL_NIGHT_ETB.budget.max,
      amenities: ['WiFi'],
      check_in: '13:00',
      check_out: '10:00',
    },
  },
  {
    id: 'demo-hotel-3',
    name: 'Lakeside Resort Band (DEMO)',
    slug: 'kuriftu-style-resort-demo',
    category_id: 'demo-hotel',
    description: `Planning example comfort / lakeside tier ~${HOTEL_NIGHT_ETB.comfort.min}–${HOTEL_NIGHT_ETB.comfort.max} ETB/night. Not affiliated with any brand.`,
    short_description: 'Planning · resort-class band',
    address: 'Lake shore area',
    latitude: 11.61,
    longitude: 37.375,
    phone: null,
    email: null,
    website: null,
    price_level: 4,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-hotel',
      name: 'Hotels',
      slug: 'hotel',
      icon: 'Hotel',
      description: null,
      sort_order: 1,
    },
    hotel: {
      id: 'demo-h-3',
      place_id: 'demo-hotel-3',
      star_rating: 4,
      minimum_price: HOTEL_NIGHT_ETB.comfort.min,
      maximum_price: HOTEL_NIGHT_ETB.comfort.max,
      amenities: ['WiFi', 'Pool', 'Restaurant', 'Lake view'],
      check_in: '14:00',
      check_out: '11:00',
    },
  },
  {
    id: 'demo-rest-1',
    name: 'Traditional Injera House (DEMO)',
    slug: 'tana-traditional-restaurant-demo',
    category_id: 'demo-restaurant',
    description: `Local-style restaurant planning tip. Plates often 50–350 ETB; daily food band ~${FOOD_PERSON_DAY_ETB.budget.typical}–${FOOD_PERSON_DAY_ETB.mid.typical} ETB/person.`,
    short_description: 'Injera & traditional dishes',
    address: 'Near pier / center',
    latitude: 11.592,
    longitude: 37.378,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-restaurant',
      name: 'Restaurants',
      slug: 'restaurant',
      icon: 'UtensilsCrossed',
      description: null,
      sort_order: 2,
    },
    restaurant: {
      id: 'demo-r-1',
      place_id: 'demo-rest-1',
      cuisine_type: 'Ethiopian',
      minimum_price: 80,
      maximum_price: 400,
      vegetarian: true,
      traditional_food: true,
      delivery_available: false,
      reservation_available: false,
    },
  },
  {
    id: 'demo-rest-2',
    name: 'Lakeside Fish (DEMO)',
    slug: 'lake-fish-grill-demo',
    category_id: 'demo-restaurant',
    description: 'Lake fish planning tip (tilapia / Nile fish). Mains often 180–500 ETB. Confirm venue on site.',
    short_description: 'Lake fish',
    address: 'Lakeside',
    latitude: 11.6005,
    longitude: 37.3825,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-restaurant',
      name: 'Restaurants',
      slug: 'restaurant',
      icon: 'UtensilsCrossed',
      description: null,
      sort_order: 2,
    },
    restaurant: {
      id: 'demo-r-2',
      place_id: 'demo-rest-2',
      cuisine_type: 'Seafood',
      minimum_price: 180,
      maximum_price: 500,
      vegetarian: false,
      traditional_food: true,
      delivery_available: false,
      reservation_available: true,
    },
  },
  {
    id: 'demo-cafe-1',
    name: 'City Coffee Stop (DEMO)',
    slug: 'city-cafe-demo',
    category_id: 'demo-cafe',
    description: 'Coffee culture tip. Coffee often 30–80 ETB.',
    short_description: 'Coffee stop',
    address: 'Main road / center',
    latitude: 11.59,
    longitude: 37.365,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-cafe',
      name: 'Cafes',
      slug: 'cafe',
      icon: 'Coffee',
      description: null,
      sort_order: 3,
    },
    restaurant: {
      id: 'demo-c-1',
      place_id: 'demo-cafe-1',
      cuisine_type: 'Cafe',
      minimum_price: 30,
      maximum_price: 150,
      vegetarian: true,
      traditional_food: false,
      delivery_available: false,
      reservation_available: false,
    },
  },
  {
    id: 'demo-pier',
    name: 'Lake Tana Boat Pier',
    slug: 'lake-tana-boat-pier',
    category_id: 'demo-transport',
    description: 'Shore area for monastery boats. Negotiate shared vs private; agree price first.',
    short_description: 'Boat departure area',
    address: 'Lake Tana shore, Bahir Dar',
    latitude: 11.605,
    longitude: 37.39,
    phone: null,
    email: null,
    website: null,
    price_level: 2,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-transport',
      name: 'Transport',
      slug: 'transport',
      icon: 'Bus',
      description: null,
      sort_order: 7,
    },
  },
  {
    id: 'demo-bus',
    name: 'Bahir Dar Bus Station',
    slug: 'bahir-dar-bus-station',
    category_id: 'demo-transport',
    description: 'Intercity buses (Addis, Gondar, etc.). Arrive early; confirm fares at the station.',
    short_description: 'Intercity bus terminal',
    address: 'Bahir Dar bus station area',
    latitude: 11.585,
    longitude: 37.38,
    phone: null,
    email: null,
    website: null,
    price_level: 1,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-transport',
      name: 'Transport',
      slug: 'transport',
      icon: 'Bus',
      description: null,
      sort_order: 7,
    },
  },
  {
    id: 'demo-airport',
    name: 'Bahir Dar Airport (BJR)',
    slug: 'bahir-dar-airport-bjr',
    category_id: 'demo-transport',
    description: 'Domestic airport. Allow 15–40 min road transfer into town.',
    short_description: 'Domestic airport',
    address: 'Bahir Dar Airport',
    latitude: 11.608,
    longitude: 37.321,
    phone: null,
    email: null,
    website: null,
    price_level: 3,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-transport',
      name: 'Transport',
      slug: 'transport',
      icon: 'Bus',
      description: null,
      sort_order: 7,
    },
  },
  {
    id: 'demo-hospital',
    name: 'Felege Hiwot Referral Hospital',
    slug: 'felege-hiwot-hospital',
    category_id: 'demo-hospital',
    description: 'Major public referral hospital. Confirm departments and visiting hours locally.',
    short_description: 'Main public hospital',
    address: 'Felege Hiwot area, Bahir Dar',
    latitude: 11.58,
    longitude: 37.37,
    phone: null,
    email: null,
    website: null,
    price_level: null,
    entrance_fee: null,
    currency: 'ETB',
    verified: false,
    featured: true,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-hospital',
      name: 'Hospitals',
      slug: 'hospital',
      icon: 'Hospital',
      description: null,
      sort_order: 8,
    },
  },
  {
    id: 'demo-center',
    name: 'Bahir Dar City Center',
    slug: 'bahir-dar-center',
    category_id: 'demo-attraction',
    description: 'City center reference point for map orientation.',
    short_description: 'City center',
    address: 'Bahir Dar',
    latitude: BAHIR_DAR_CENTER.lat,
    longitude: BAHIR_DAR_CENTER.lng,
    phone: null,
    email: null,
    website: null,
    price_level: null,
    entrance_fee: 0,
    currency: 'ETB',
    verified: false,
    featured: false,
    status: 'published',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: {
      id: 'demo-attraction',
      name: 'Attractions',
      slug: 'attraction',
      icon: 'Landmark',
      description: null,
      sort_order: 4,
    },
  },
]

/** Alias used by fast path — same as DEMO_PLACES */
export const CURATED_PLACES = DEMO_PLACES

export function demoPlacesByCategory(slug: string): Place[] {
  return DEMO_PLACES.filter((p) => p.category?.slug === slug)
}
