import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

let failed = 0
function ok(cond, msg) {
  if (cond) console.log('  ok', msg)
  else {
    console.error('  FAIL', msg)
    failed++
  }
}

console.log('Digital Bahir Dar smoke checks')

// PWA shell
ok(existsSync(join(process.cwd(), 'public', 'sw.js')), 'public/sw.js')
ok(existsSync(join(process.cwd(), 'public', 'manifest.webmanifest')), 'manifest')
ok(existsSync(join(process.cwd(), 'public', 'offline.html')), 'offline.html')

// Icons generated by prebuild or npm run icons (optional in pure clone)
const icon192 = existsSync(join(process.cwd(), 'public', 'pwa-192.png'))
const icon512 = existsSync(join(process.cwd(), 'public', 'pwa-512.png'))
if (icon192 && icon512) {
  ok(true, 'PWA icons present')
} else {
  console.log('  skip PWA icons (run npm run icons / prebuild)')
}

const migrations = readdirSync(join(process.cwd(), 'supabase/migrations')).filter((f) =>
  f.endsWith('.sql')
)
ok(migrations.length >= 6, 'migrations >= 6 got ' + migrations.length)

const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
ok(/^1\.\d+\.\d+$/.test(pkg.version), `version 1.x.x (got ${pkg.version})`)
ok(typeof pkg.scripts?.prebuild === 'string', 'prebuild script')
ok(typeof pkg.scripts?.smoke === 'string', 'smoke script')

ok(existsSync('LAUNCH.md'), 'LAUNCH.md')
ok(existsSync('vercel.json'), 'vercel.json')
ok(existsSync('.env.example'), '.env.example')
ok(existsSync('src/App.tsx'), 'src/App.tsx')
ok(existsSync('src/components/feedback/StateMessage.tsx'), 'StateMessage')
ok(existsSync('src/pages/Restaurants/index.tsx'), 'Restaurants page')
ok(existsSync('src/pages/Hotels/index.tsx'), 'Hotels page')
ok(existsSync('src/lib/supabase.ts'), 'supabase client')

// Critical route modules exist (lazy-loaded pages)
const routes = [
  'src/pages/Home/index.tsx',
  'src/pages/Map/index.tsx',
  'src/pages/Explore/index.tsx',
  'src/pages/AIGuide/index.tsx',
  'src/pages/Admin/index.tsx',
  'src/pages/TripPlanner/index.tsx',
  'src/pages/Auth/index.tsx',
]
for (const r of routes) {
  ok(existsSync(r), r)
}

// App uses Suspense / lazy for code splitting
const appSrc = readFileSync('src/App.tsx', 'utf8')
ok(appSrc.includes('lazy(') && appSrc.includes('Suspense'), 'App uses React.lazy + Suspense')

console.log(failed ? failed + ' failed' : 'All smoke checks passed')
process.exit(failed ? 1 : 0)
